# Generated by Django 3.2.3 on 2021-10-03 16:03

import api.models
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.upload_post_path)),
                ('text', models.CharField(max_length=30)),
                ('main_text', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開する')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
